apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: mlflow123
  POSTGRES_DB: mlflow
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123
  MLFLOW_BUCKET: mlflow-artifacts
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin123
  AWS_DEFAULT_REGION: us-east-1
  S3_ENDPOINT_URL: http://minio.mlops.svc.cluster.local:9000
