name: Build & Push Training Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout research repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout platform repo (for Dockerfile)
        uses: actions/checkout@v4
        with:
          repository: MLops-Project-Platform/mlops-platform
          ref: main
          path: mlops-platform
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide environment suffix (prod/qa/dev)
        id: env
        shell: bash
        run: |
          set -euo pipefail
          git fetch --all --tags
          SHA="${GITHUB_SHA}"

          # האם ה-commit נמצא ב-main או ב-qa?
          if git branch -r --contains "$SHA" | grep -q "origin/main"; then
            echo "suffix=prod" >> "$GITHUB_OUTPUT"
          elif git branch -r --contains "$SHA" | grep -q "origin/qa"; then
            echo "suffix=qa" >> "$GITHUB_OUTPUT"
          else
            echo "suffix=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: mlops-platform/${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ghcr.io/mlops-project-platform/${{ inputs.image_name }}:${{ github.ref_name }}-${{ steps.env.outputs.suffix }}
            ghcr.io/mlops-project-platform/${{ inputs.image_name }}:${{ github.sha }}
